# Generated by Django 6.1 on 2026-08-27 20:41

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['view_type', '-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(default=cars.models.generate_sale_reference, max_length=20, unique=True),
        ),
    ]
