# Generated by Django 6.1 on 2026-08-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_payment_chapa_checkout_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='chapa_checkout_url',
        ),
    ]
